name: Deploy Stage

on:
  push:
    tags:
      - 'v*-stage'

jobs:

  build:

    runs-on: ubuntu-latest
    environment: stage    
    steps:
    - uses: actions/checkout@v3
    - name: Get Secrets      
      run: echo ${{ secrets.AWS_EXPORTS }} | base64 -d > src/aws-exports.js
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag melvinrmc/casadeoracion:${{  github.ref_name }}
    - name: Docker Push
      run: docker push melvinrmc/casadeoracion:${{  github.ref_name }}
